# Generated by Django 4.2.7 on 2026-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_subject_alter_notification_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Когда уведомление должно быть отправлено', null=True),
        ),
    ]
